In [11]:
# Import all the necessary libraries

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Flatten, Dense

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.metrics import confusion_matrix, accuracy_score

In [22]:
# load the dataset

dataset = pd.read_csv('D:\practice\churn.csv')

In [13]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [23]:
# Selecting features and target from the raw data
# Remove columns that does not add any value to the prediction

X = dataset.drop(labels=['CustomerId', 'Surname', 'RowNumber', 'Exited'], axis = 1)
y = dataset['Exited']

In [15]:
X.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [16]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [24]:
# Checking distinct values for Geography and Gender

X['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [25]:
X['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [26]:
# Label encoding geography and gender features

geo_label = LabelEncoder()
X['Geography'] = geo_label.fit_transform(X['Geography'])

gender_label = LabelEncoder()
X['Gender'] = gender_label.fit_transform(X['Gender'])

In [20]:
X.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          2       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          2       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [27]:
# One hot encode Geography column 

X = pd.get_dummies(X, columns=['Geography'])
X.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Geography_0  Geography_1  Geography_2  
0               1        101348.88            1            0            0  
1               1        112542.58            0            0            1  
2               0        113931.57            1            0            0  
3               0         93826.63            1            0            0  
4               1         79084.10            0            0            1

In [28]:
# Splitting data 80/20 : 80 % training and 20 % testing 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0, stratify = y)

In [29]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [30]:
X_train

array([[-1.24021723, -1.09665089,  0.77986083, ...,  0.998002  ,
        -0.57812007, -0.57504086],
       [ 0.75974873,  0.91186722, -0.27382717, ..., -1.002002  ,
         1.72974448, -0.57504086],
       [-1.72725557, -1.09665089, -0.9443559 , ...,  0.998002  ,
        -0.57812007, -0.57504086],
       ...,
       [-0.51484098,  0.91186722,  0.87565065, ..., -1.002002  ,
         1.72974448, -0.57504086],
       [ 0.73902369, -1.09665089, -0.36961699, ...,  0.998002  ,
        -0.57812007, -0.57504086],
       [ 0.95663657,  0.91186722, -1.32751517, ..., -1.002002  ,
        -0.57812007,  1.73900686]])

In [31]:
X.shape[1]

12

In [32]:
# Building Artificial Neural Network ANN

model = Sequential()
model.add(Dense(X.shape[1], activation='relu', input_dim = X.shape[1]))
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation = 'sigmoid'))

In [34]:
# Compiling Model 

model.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])

In [36]:
# Fitting the model

model.fit(X_train, y_train.to_numpy(), batch_size = 20, epochs = 20, verbose = 1)

Epoch 1/20
400/400 [==============================] - 1s 1ms/step - loss: 0.3278 - accuracy: 0.8648
Epoch 2/20
400/400 [==============================] - 1s 2ms/step - loss: 0.3272 - accuracy: 0.8654
Epoch 3/20
400/400 [==============================] - 1s 1ms/step - loss: 0.3264 - accuracy: 0.8643
Epoch 4/20
400/400 [==============================] - 1s 2ms/step - loss: 0.3256 - accuracy: 0.8656: 0s - loss: 0.324
Epoch 5/20
400/400 [==============================] - 1s 2ms/step - loss: 0.3252 - accuracy: 0.8641
Epoch 6/20
400/400 [==============================] - 1s 2ms/step - loss: 0.3247 - accuracy: 0.8677
Epoch 7/20
400/400 [==============================] - 1s 1ms/step - loss: 0.3240 - accuracy: 0.8664
Epoch 8/20
400/400 [==============================] - 1s 2ms/step - loss: 0.3237 - accuracy: 0.8658: 0s - loss: 0.3156 - ac
Epoch 9/20
400/400 [==============================] - 1s 1ms/step - loss: 0.3226 - accuracy: 0.8660
Epoch 10/20
400/400 [==============================] - 1s 

In [37]:
# Testing model on Xtest

y_pred = model.predict_classes(X_test)

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [38]:
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [1],
       [0]])

In [39]:
y_test

1344    1
8167    0
4747    0
5004    1
3124    1
       ..
9107    0
8249    0
8337    0
6279    1
412     0
Name: Exited, Length: 2000, dtype: int64

In [40]:
# Calculating model loss and accuracy

model.evaluate(X_test, y_test.to_numpy())

63/63 [==============================] - 0s 1ms/step - loss: 0.3557 - accuracy: 0.8580


[0.35567429661750793, 0.8579999804496765]

In [41]:
# Building confusion matrix

confusion_matrix(y_test, y_pred)

array([[1506,   87],
       [ 197,  210]], dtype=int64)

In [42]:
# Printing Accuracy score

accuracy_score(y_test, y_pred)

0.858